version: '3'
services:
  app:
    image: tiennm/nginx-php-8.1:0.0.14
    working_dir: /var/www/html
    volumes:
        - ./:/var/www/html
    ports:
        - 80:80
    networks:
        - api
  mysql:
    image: mysql:8.0
    environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: api
    volumes:
        - ./docker/mysql/data/:/var/lib/mysql
    ports:
        - 3306:3306
    networks:
        - api
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
        - api
    depends_on:
      - mysql

networks:
  api:
    driver: bridge
